/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited manually.
// See https://nextjs.org/docs/app/building-your-application/configuring/typescript
// for more information.

// NOTE: This file should not be checked into version control
// as it is automatically generated by Next.js.
// To avoid this, add it to your .gitignore file.
